"""parole forte

Revision ID: 014b17fdac5b
Revises: e3f2767c8533
Create Date: 2025-04-05 14:51:25.476129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014b17fdac5b'
down_revision: Union[str, None] = 'e3f2767c8533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strong_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strong_words_id'), 'strong_words', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strong_words_id'), table_name='strong_words')
    op.drop_table('strong_words')
    # ### end Alembic commands ###
