"""Initial migration

Revision ID: 9af53745181c
Revises: 
Create Date: 2025-03-29 13:09:44.518667

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af53745181c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('image', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('name', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('description', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('area', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'communities', ['name'])
    op.add_column('users', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'community_id')
    op.drop_constraint(None, 'communities', type_='unique')
    op.drop_column('communities', 'is_active')
    op.drop_column('communities', 'area')
    op.drop_column('communities', 'description')
    op.drop_column('communities', 'name')
    op.drop_column('communities', 'image')
    # ### end Alembic commands ###
