"""parole forte update

Revision ID: 9cf4c2ed33f5
Revises: 014b17fdac5b
Create Date: 2025-04-05 15:13:57.957448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf4c2ed33f5'
down_revision: Union[str, None] = '014b17fdac5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strong_words', 'sentence',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('strong_words', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strong_words', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('strong_words', 'sentence',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
