"""add can_add and can_edit to users

Revision ID: eecf3b72f813
Revises: b7b18386b294
Create Date: 2025-04-05 20:26:32.758051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecf3b72f813'
down_revision: Union[str, None] = 'b7b18386b294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('is_communication', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_add', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_edit', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'can_edit')
    op.drop_column('users', 'can_add')
    op.drop_column('communities', 'is_communication')
    # ### end Alembic commands ###
